# Generated by Django 4.0.6 on 2022-07-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_customer_message_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='message',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
